import http from "node:http";

const port=Number(process.env.PORT||8787);
const supabaseUrl=process.env.SUPABASE_URL||"";
const anonKey=process.env.SUPABASE_ANON_KEY||"";
const corsOrigin=process.env.CORS_ORIGIN||"http://localhost:4173";
function send(res,status,body){res.writeHead(status,{"Content-Type":"application/json","Access-Control-Allow-Origin":corsOrigin,"Access-Control-Allow-Headers":"authorization,content-type","Access-Control-Allow-Methods":"GET,POST,PATCH,OPTIONS"});res.end(JSON.stringify(body));}
function auth(req){return req.headers.authorization||`Bearer ${anonKey}`;}
async function db(path,request,options={}){const response=await fetch(`${supabaseUrl}/rest/v1/${path}`,{...options,headers:{apikey:anonKey,Authorization:auth(request),"Content-Type":"application/json",...(options.headers||{})}});const text=await response.text();let data=null;try{data=text?JSON.parse(text):null;}catch{}if(!response.ok)throw Object.assign(new Error(data?.message||"Supabase request failed"),{status:response.status});return data;}
async function body(req){let value="";for await(const chunk of req)value+=chunk;return value?JSON.parse(value):{};}
http.createServer(async(req,res)=>{if(req.method==="OPTIONS"){send(res,204,{});return;}if(!req.url.startsWith("/api/")){send(res,404,{error:"Not found"});return;}if(!supabaseUrl||!anonKey){send(res,503,{error:"Backend is not configured."});return;}try{const url=new URL(req.url,`http://${req.headers.host}`);const tracking=url.pathname.match(/^\/api\/tracking\/([^/]+)$/);if(req.method==="GET"&&tracking){const rows=await db(`shipments?select=*&tracking_number=eq.${encodeURIComponent(decodeURIComponent(tracking[1]))}&limit=1`,req);if(!rows?.[0]){send(res,404,{error:"Shipment not found"});return;}const events=await db(`shipment_events?select=*&shipment_id=eq.${rows[0].id}&order=created_at.desc`,req);send(res,200,{shipment:rows[0],events});return;}if(!req.headers.authorization){send(res,401,{error:"Authentication required"});return;}if(req.method==="GET"&&url.pathname==="/api/admin/shipments"){send(res,200,{shipments:await db("shipments?select=*&order=created_at.desc",req)});return;}const shipment=url.pathname.match(/^\/api\/admin\/shipments\/([^/]+)$/);if(req.method==="PATCH"&&shipment){const patch=await body(req);send(res,200,{shipment:(await db(`shipments?id=eq.${shipment[1]}`,req,{method:"PATCH",body:JSON.stringify({...patch,updated_at:new Date().toISOString()}),headers:{Prefer:"return=representation"}}))?.[0]||null});return;}if(req.method==="DELETE"&&shipment){await db(`shipments?id=eq.${shipment[1]}`,req,{method:"DELETE"});send(res,204,{});return;}if(req.method==="POST"&&url.pathname==="/api/driver/location"){const value=await body(req);const location=await db("driver_locations",req,{method:"POST",body:JSON.stringify(value),headers:{Prefer:"return=representation"}});if(value.shipment_id)await db(`shipments?id=eq.${value.shipment_id}`,req,{method:"PATCH",body:JSON.stringify({current_lat:value.latitude,current_lng:value.longitude,updated_at:new Date().toISOString()})});send(res,201,{location:location?.[0]||null});return;}send(res,404,{error:"Route not found"});}catch(error){send(res,error.status||500,{error:error.message});}}).listen(port,()=>console.log(`Swift Courier backend listening on ${port}`));
